# ?? ??
server:
  port: 9999
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# MySQL
spring:
  # 메일 요청을 위한 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: coala1080@gmail.com
    # plz not update, don't remember
    password: wousleleumelwfft
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 600000

  redis:
    host: myredis
    port: 6379

  main:
    allow-bean-definition-overriding: true

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  # datasource
  datasource:
#    url: jdbc:mysql://localhost:3306/gudgement?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    # 한국시간으로 DB저장되게 !!
#    url: jdbc:mysql://localhost:3306/gudgement?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
#    username: root
#    password: ssafy

    url: jdbc:mysql://database-1.cjfyk8ntjeyl.ap-northeast-2.rds.amazonaws.com:3306/gudgement?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: gudgement
    password: d106gudgement
    driver-class-name: com.mysql.cj.jdbc.Driver

#    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver

  # Jpa
  jpa:
    show-sql: true

    # Hibernate
    database: mysql
    hibernate:
      # ?? ?? ? create ? DB??? ???.
      ddl-auto: update
      # camelcase ??
      strategy: org.hibernate.cfg.ImprovedNamingStrategy
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # ddl-auto ?? ?? ??
      generate-ddl: true
    # SQL? ?? ??
    properties:
      hibernate:
        format_sql: true
      # LazyInitializationException ??
      enable_lazy_load_no_trans: true

  oauth2:
    client:
      registration:
        kakao:
          client-id: 4cd45261b839373b375e0766220b3428
          redirect-uri: http://j9d106.p.ssafy.io:8080/oauth/login/auth/kakao/callback
          client-authentication-method: POST
          authorization-grant-type: authorization_code
          scope: account_email
          client-secret: IxXm1l2rPYcLXojdZmL9MXr8bmTkEmPQ
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com

# spring-docs
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true

jwt:
  secret:
    key: javax.crypto.spec.SecretKeySpec@fa7605b8



# H2 ??? ??? ?? ???
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.jpa.show-sql=true
#spring.hibernate.ddl-auto=none

# yml push 안되게 설정 2트.