# ?? ??
server:
  port: 9999
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# MySQL
spring:
  # 메일 요청을 위한 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: coala1080@gmail.com
    # plz not update, don't remember
    password: {비밀번호}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 600000

  redis:
    host: myredis
    port: 6379

  main:
    allow-bean-definition-overriding: true

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  # datasource
  datasource:
    url: {주소}
    username: gudgement
    password: {비밀번호}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Jpa
  jpa:
    show-sql: true

    # Hibernate
    database: mysql
    hibernate:
      # ?? ?? ? create ? DB??? ???.
      ddl-auto: update
      # camelcase ??
      strategy: org.hibernate.cfg.ImprovedNamingStrategy
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # ddl-auto ?? ?? ??
      generate-ddl: true
    # SQL? ?? ??
    properties:
      hibernate:
        format_sql: true
      # LazyInitializationException ??
      enable_lazy_load_no_trans: true

  oauth2:
    client:
      registration:
        kakao:
          client-id: {클라이언트 ID}
          redirect-uri: http://j9d106.p.ssafy.io:8080/
          client-authentication-method: POST
          authorization-grant-type: authorization_code
          scope: account_email
          client-secret: {클라이언트 시크릿릿}
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com

# spring-docs
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true

jwt:
  secret:
    key: javax.crypto.spec.SecretKeySpec@fa7605b8

# H2 ??? ??? ?? ???
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.jpa.show-sql=true
#spring.hibernate.ddl-auto=none

